/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-QL.h
 #	source generated by 4D Plugin Wizard
 #	Project : QL
 #	author : miyako
 #	2019/12/01
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_QL_H
#define PLUGIN_QL_H

#include "4DPluginAPI.h"

#import <Quartz/Quartz.h>

#include "4DPlugin-JSON.h"
#include "json/json.h"

#pragma mark -

void QL_Create_thumbnail(PA_PluginParameters params);

#endif /* PLUGIN_QL_H */
